version: '3'
services:
  database:
    image: postgres:9.6
    volumes:
    - "../volumes/database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: casurp
      POSTGRES_PASSWORD: casurp
      POSTGRES_DB: casurp
  web:
    build:
      context: .
      dockerfile: Dockerfile
    user: $UID
    tty: true
    ports:
    - "8889:80"
    - "8080:8000"
    depends_on:
    - database
    volumes:
    - "../..:/casurp"
    working_dir: /casurp
    restart: unless-stopped
    command: bash -c "bash /casurp/docker/casurp/init_dev.sh -d && php /casurp/bin/console server:run 0.0.0.0:8000"