<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEl5gbxU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEl5gbxU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEl5gbxU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEl5gbxU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEl5gbxU\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'El5gbxU',
    'container.build_id' => 'e8ddbd68',
    'container.build_time' => 1533275591,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEl5gbxU');
